[metadata]
name    = "storm"
author  = "ave"

[global]
plan    = "storm"
case    = "storm"
builder = "docker:go"
runner  = "cluster:k8s"
total_instances = 10000

[global.build_config]
push_registry=true
go_proxy_mode="direct"
registry_type="aws"

[global.run_config]


[[groups]]
id = "first"
instances = { count = 10000 }

  [groups.resources]
  memory = '150Mi'
  cpu = '100m'

  [groups.run.test_params]
  conn_count = '10'
  conn_outgoing = '50'
  conn_delay_ms = '20000'
  concurrent_dials = '5'
  data_size_kb     = '10'
